### ISSUE TITLE
Remote control app script

### ISSUE THREAD

**Issue by albakar** [DIT112-V21/group-13#4]
- As a user I want a bug free app so that when I run the app I won’t have any problems.

**Comment by albakar** [comment]
- As a user I want a bug free app so that when I run the app I won’t have any problems.

**Comment by platisd** [comment]
> * As a user I want a bug free app so that when I run the app I won’t have any problems.

Please include this in the issue's description

**Comment by platisd** [comment]
Also, the description sounds different from the tittle. Is this in the correct place?
Also, this doesn't sound like a feature but more like a non functional requirement that still needs some metrics to be unambiguously specified.

**Comment by albakar** [comment]
I couldn't figure out how to add a description after I submit the issue. so I put it as a comment, don't know if there is any way around.
About if it is in a right place we are going to take another look at it with the work group and consider your comment.

**Comment by platisd** [comment]
![Screenshot_20210404_161738_com android chrome](https://user-images.githubusercontent.com/7327776/113511678-4eb84e80-9561-11eb-939b-c60ec5d67ec8.jpg)
